CREATE TABLE IF NOT EXISTS `#__jpframework_blocks` (
`id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT,
`title` VARCHAR(150)  NOT NULL DEFAULT '',
`uniqid` VARCHAR(50)  NOT NULL DEFAULT '',
`ordering` INT(11)  NOT NULL DEFAULT 0,
`state` TINYINT(1)  NOT NULL DEFAULT 0,
`checked_out` INT(11)  NOT NULL DEFAULT 0,
`checked_out_time` DATETIME NOT NULL DEFAULT '0000-00-00 00:00:00',
`created_by` INT(11)  NOT NULL DEFAULT 0,
`type` VARCHAR(255)  NOT NULL DEFAULT '',
`position` VARCHAR(50)  NOT NULL DEFAULT '',
`language` CHAR(7)  NOT NULL DEFAULT '' ,
`menuitem` VARCHAR(50)  NOT NULL DEFAULT '0',
`params` TEXT NOT NULL DEFAULT '',
PRIMARY KEY (`id`)
) DEFAULT COLLATE=utf8_general_ci;
